### ISSUE TITLE
Allow adding a font file instead of just the name in the style file

### ISSUE THREAD

**Issue by bennyboer** [bennyboer/thaw#48]
I want to add a custom font file in the style file:

```css
document {
  font-family: url(my-font-file.ttf);
}
```

**Comment by bennyboer** [comment]
# Example

For all font-family properties you can not specify the font family name as well as the URL of where to find a bunch of font files (or just one).

font-family: Playfair Display:url(res/fonts/playfair_display); is an example.

### TDS
```css
document {
  font-family: Playfair Display:url(res/fonts/playfair_display); // When specifying a folder, all the included font files will be added to the Thaw font manager (the preferred font-variant from the font-variant property will be used)
  inline-code-font-family: Consolas;
  line-number-font-family: Playfair Display:url(res/fonts/playfair_display/PlayfairDisplay-Medium.ttf); // Specify a file directly thus overriding the preferred font variant set by the font-variant property
}
```
